version: 2
jobs:
  php-7.1-apache:
    docker:
      - image: php:7.1-apache
        environment:
          - DB_DATABASE: testing
          - DB_USERNAME: testing
          - DB_PASSWORD: testing
          - APP_KEY: deela5kinohw0haekoothahSh8eexach

    working_directory: ~/repo

    steps:
      - checkout

      - run: service mysql start
      - run: mysql -e "create database if not exists testing;"
      - run: mysql -e "create or replace user testing@localhost identified by 'testing';"
      - run: mysql -e "grant all privileges on *.* to testing@localhost with grant option;"
      - run: composer config -g github-oauth.github.com $GITHUB_TOKEN
      - run: composer install -n --prefer-dist --no-progress -o
      - run: ./vendor/bin/phpunit

workflows:
  version: 2
  test:
    jobs:
      - php-7.1-apache