version: 2

jobs:
    "php-7.1-apache":
        docker:
        - image: phpearth/php:7.1-apache
          environment:
            - DB_DATABASE: testing
            - DB_USERNAME: testing
            - DB_PASSWORD: testing
            - APP_KEY: deela5kinohw0haekoothahSh8eexach
        - image: mariadb:latest
          environment:
            - MYSQL_DATABASE: testing
            - MYSQL_USER: testing
            - MYSQL_PASSWORD: testing
            - MYSQL_ROOT_PASSWORD: testing
        - image: postgres:latest
          environment:
            - POSTGRES_DB: testing
            - POSTGRES_USER: testing
            - POSTGRES_PASSWORD: testing
        working_directory: ~/repo
        steps:
            - checkout
            - run:
                command: apk add --no-cache mysql-client gd composer php7.1-pdo_mysql php7.1-pdo_pgsql
#            - run: mysql -e "grant all privileges on *.* to testing@localhost with grant option;"
            - run: composer config -g github-oauth.github.com $GITHUB_TOKEN
            - run: composer install -n --prefer-dist --no-progress -o
            - run: php tests/scripts/setup.php
#            - run: DB_CONNECTION=mysql ./vendor/bin/phpunit -c ci.phpunit.xml
            - run: DB_CONNECTION=pgsql ./vendor/bin/phpunit -c ci.phpunit.xml

workflows:
    version: 2
    test:
        jobs:
            - "php-7.1-apache"
